//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `APP_DEBUG_CONFIG.plist`.
    static let app_DEBUG_CONFIGPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "APP_DEBUG_CONFIG", pathExtension: "plist")
    /// Resource file `APP_RELEASE_CONFIG.plist`.
    static let app_RELEASE_CONFIGPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "APP_RELEASE_CONFIG", pathExtension: "plist")
    
    /// `bundle.url(forResource: "APP_DEBUG_CONFIG", withExtension: "plist")`
    static func app_DEBUG_CONFIGPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.app_DEBUG_CONFIGPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "APP_RELEASE_CONFIG", withExtension: "plist")`
    static func app_RELEASE_CONFIGPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.app_RELEASE_CONFIGPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `BandDetailCell`.
    static let bandDetailCell: Rswift.ReuseIdentifier<BandDetailCell> = Rswift.ReuseIdentifier(identifier: "BandDetailCell")
    /// Reuse identifier `BandSearchCell`.
    static let bandSearchCell: Rswift.ReuseIdentifier<BandSearchCell> = Rswift.ReuseIdentifier(identifier: "BandSearchCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 4 storyboards.
  struct storyboard {
    /// Storyboard `BandDetail`.
    static let bandDetail = _R.storyboard.bandDetail()
    /// Storyboard `BandSearch`.
    static let bandSearch = _R.storyboard.bandSearch()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "BandDetail", bundle: ...)`
    static func bandDetail(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.bandDetail)
    }
    
    /// `UIStoryboard(name: "BandSearch", bundle: ...)`
    static func bandSearch(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.bandSearch)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct bandDetail: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = BandDetailViewController
      
      let bundle = R.hostingBundle
      let name = "BandDetail"
      
      fileprivate init() {}
    }
    
    struct bandSearch: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "BandSearch"
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceType {
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
